In [1]:
import torch
import numpy as np

In [ ]:
data = [[1, 2], [3, 4]]
data_np = np.array(data)
data_ts = torch.tensor(data)
tensor_from_np = torch.from_numpy(data_np)

print(">>initial data \n",data)
print(">>Numpy Array \n", data_np)
print(">>Tensor from list \n", data_ts)
print(">>Tensor from ndarray \n", tensor_from_np)

>> initial data 
 [[1, 2], [3, 4]]
>> Numpy Array 
 [[1 2]
 [3 4]]
>> Tensor from list 
 tensor([[1, 2],
        [3, 4]])
>> Tensor from ndarray 
 tensor([[1, 2],
        [3, 4]])


In [6]:
x = torch.tensor(data)

In [10]:
print(">>Shape:", x.shape)

>>Shape: torch.Size([2, 2])


In [18]:
print(f">> Ones-likes: \n {torch.ones_like(x)}")

>> Ones-likes: 
 tensor([[1, 1],
        [1, 1]])


In [17]:
print(f">> Random tensor: \n {torch.rand_like(x, dtype=torch.float)}")

>> Random tensor: 
 tensor([[0.6515, 0.1570],
        [0.8154, 0.9743]])


In [25]:
shape = (3, 2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f">> Random Tensor: \n {rand_tensor} \n")
print(f">> Ones Tensor: \n {ones_tensor} \n")
print(f">> Zeros Tensor: \n {zeros_tensor}")

>> Random Tensor: 
 tensor([[[0.0292, 0.2027, 0.3881],
         [0.8044, 0.5959, 0.3903]],

        [[0.9159, 0.2041, 0.6543],
         [0.5172, 0.1977, 0.0570]],

        [[0.4318, 0.1023, 0.4879],
         [0.5187, 0.3780, 0.7560]]]) 

>> Ones Tensor: 
 tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]) 

>> Zeros Tensor: 
 tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [34]:
x1 = torch.rand(2, 3)
print(f".. x1: \n {x1}")
print(f".. Size of x1: {x1.shape}")
print(f".. x1 elements type: {x1.dtype}")
print(f".. Device we're are running on: {x1.device}")

.. x1: 
 tensor([[0.8639, 0.4228, 0.3356],
        [0.1308, 0.4472, 0.4575]])
.. Size of x1: torch.Size([2, 3])
.. x1 elements type: torch.float32
.. Device we're are running on: cpu


In [35]:
if torch.cuda.is_available():
    x = x.to('cuda')
    print(f".. Device tensor is stored in {x.device}")
else: 
    print(f".. Device tensor is stored in {x.device}")

.. Device tensor is stored in cpu


In [36]:
x[:, 1] = 0
print(x)

tensor([[1, 0],
        [3, 0]])


In [38]:
torch.concat([x, x, x], dim=1)

tensor([[1, 0, 1, 0, 1, 0],
        [3, 0, 3, 0, 3, 0]])

In [39]:
torch.concat([x, x, x], dim=0)

tensor([[1, 0],
        [3, 0],
        [1, 0],
        [3, 0],
        [1, 0],
        [3, 0]])

In [40]:
x[:, 1] = 2
x.mul(x)

tensor([[1, 4],
        [9, 4]])

In [41]:
x * x

tensor([[1, 4],
        [9, 4]])

In [42]:
x.matmul(x)

tensor([[ 7,  6],
        [ 9, 10]])

In [43]:
x @ x

tensor([[ 7,  6],
        [ 9, 10]])

In [44]:
x1 = torch.rand(2, 3)

In [45]:
x.shape, x1.shape

(torch.Size([2, 2]), torch.Size([2, 3]))

In [47]:
x.dtype, x1.dtype

(torch.int64, torch.float32)

In [50]:
x = x.to(torch.float32)

In [52]:
x.matmul(x1)

tensor([[1.9394, 0.5546, 2.3000],
        [2.6235, 1.2710, 3.9988]])

In [53]:
x @ x1

tensor([[1.9394, 0.5546, 2.3000],
        [2.6235, 1.2710, 3.9988]])

In [55]:
x2 = torch.rand(3, 3)

In [57]:
x1.matmul(x2), x1 @ x2

(tensor([[1.1904, 1.2040, 0.5635],
         [1.0717, 0.9457, 0.4888]]),
 tensor([[1.1904, 1.2040, 0.5635],
         [1.0717, 0.9457, 0.4888]]))

In [59]:
x2.matmul(x1.T), x2 @ x1.T

(tensor([[0.4794, 0.5576],
         [1.1895, 1.1603],
         [0.8559, 1.0258]]),
 tensor([[0.4794, 0.5576],
         [1.1895, 1.1603],
         [0.8559, 1.0258]]))

In [63]:
x

tensor([[10., 11.],
        [12., 11.]])

In [65]:
x.add_(-5)

tensor([[0., 1.],
        [2., 1.]])

In [66]:
t = x
n = t.numpy()

t, n

(tensor([[0., 1.],
         [2., 1.]]),
 array([[0., 1.],
        [2., 1.]], dtype=float32))

In [67]:
t.add_(2)

t, n

(tensor([[2., 3.],
         [4., 3.]]),
 array([[2., 3.],
        [4., 3.]], dtype=float32))

In [69]:
n = np.ones(5)
t = torch.from_numpy(n)

n, t

(array([1., 1., 1., 1., 1.]),
 tensor([1., 1., 1., 1., 1.], dtype=torch.float64))

In [70]:
np.add(n, 2, out=n)

n, t

(array([3., 3., 3., 3., 3.]),
 tensor([3., 3., 3., 3., 3.], dtype=torch.float64))

In [71]:
x.ndim

2

In [74]:
torch.rand((2, 4, 5)).ndim

3